name: todos_repository_local_storage
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  todos_repository_core:
    path: ../todos_repository_core
  rxdart: ^0.27.3
  shared_preferences:

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  mockito:
