// Mocks generated by Mockito 5.0.17 from annotations
// in rx_bloc_library/test/feature_stats/mocks/stats_bloc_mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rx_bloc/rx_bloc.dart' as _i4;
import 'package:rx_bloc_library/base/models/models.dart' as _i5;
import 'package:rx_bloc_library/feature_stats/blocs/stats_bloc.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeStatsBlocEvents_0 extends _i1.Fake implements _i2.StatsBlocEvents {}

class _FakeStatsBlocStates_1 extends _i1.Fake implements _i2.StatsBlocStates {}

/// A class which mocks [StatsBlocEvents].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsBlocEvents extends _i1.Mock implements _i2.StatsBlocEvents {
  MockStatsBlocEvents() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void fetchStats() => super.noSuchMethod(Invocation.method(#fetchStats, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [StatsBlocStates].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsBlocStates extends _i1.Mock implements _i2.StatsBlocStates {
  MockStatsBlocStates() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Exception> get errors =>
      (super.noSuchMethod(Invocation.getter(#errors),
          returnValue: Stream<Exception>.empty()) as _i3.Stream<Exception>);
  @override
  _i3.Stream<_i4.Result<_i5.StatsModel>> get stats =>
      (super.noSuchMethod(Invocation.getter(#stats),
              returnValue: Stream<_i4.Result<_i5.StatsModel>>.empty())
          as _i3.Stream<_i4.Result<_i5.StatsModel>>);
}

/// A class which mocks [StatsBlocType].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsBlocType extends _i1.Mock implements _i2.StatsBlocType {
  MockStatsBlocType() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatsBlocEvents get events =>
      (super.noSuchMethod(Invocation.getter(#events),
          returnValue: _FakeStatsBlocEvents_0()) as _i2.StatsBlocEvents);
  @override
  _i2.StatsBlocStates get states =>
      (super.noSuchMethod(Invocation.getter(#states),
          returnValue: _FakeStatsBlocStates_1()) as _i2.StatsBlocStates);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
